export const products = [
  {
    id: 1,
    name: "Apple Earphones",
    description: "Noise-cancellation, 40-hour battery",
    rating: 4.5,
    price: "$299.99",
    imgSrc: "./src/assets/image/apple_earphone_image.png",
  },
  {
    id: 2,
    name: "Bose QuietComfort 45",
    description: "Noise Cancellation, 24-hour battery",
    rating: 3,
    price: "$329.99",
    imgSrc: "./src/assets/image/bose_headphone_image.png",
  },
  {
    id: 3,
    name: "Samsung Galaxy S23",
    description: "Fitness Tracking, AMOLED Display",
    rating: 3.5,
    price: "$799.99",
    imgSrc: "./src/assets/image/samsung_s23phone_image.png",
  },
  {
    id: 4,
    name: "Garmin Venu 2",
    description: "Fitness Tracker, AMOLED Display",
    rating: 2,
    price: "$349.99",
    imgSrc: "./src/assets/image/venu_watch_image.png",
  },
  {
    id: 5,
    name: "PlayStation 5",
    description: "Ultra-HD, 825GB SSD, Ray Graphics",
    rating: 4.7,
    price: "$499.99",
    imgSrc: "./src/assets/image/playstation_image.png",
  },
  {
    id: 6,
    name: "Canon EOS R5",
    description: "45MP Sensor, 8K Video Recording",
    rating: 3,
    price: "$3,899.99",
    imgSrc: "./src/assets/image/cannon_camera_image.png",
  },
  {
    id: 7,
    name: "MacBook Pro 16",
    description: "M2 Pro Chip, 16GB RAM, 512GB SSD",
    rating: 4.5,
    price: "$2,499.99",
    imgSrc: "./src/assets/image/macbook_image.png",
  },
  {
    id: 8,
    name: "Sony WF-1000XM5",
    description: "Noise-Cancellation, Hi-Res Audio",
    rating: 3.9,
    price: "$299.99",
    imgSrc: "./src/assets/image/sony_airbuds_image.png",
  },
  {
    id: 9,
    name: "Samsung Projector 4K",
    description: "4K Ultra HD, Realistic, Built-In Speaker",
    rating: 3,
    price: "$1,499.99",
    imgSrc: "./src/assets/image/projector_image.png",
  },
  {
    id: 10,
    name: "ASUS ROG Zephyrus G16",
    description: "Intel Core i9, RTX 4070, 16GB, 1TB",
    rating: 3,
    price: "$1,999.99",
    imgSrc: "./src/assets/image/asus_laptop_image.png",
  },
  {
    id: 11,
    name: "Google Pixel 7",
    description: "Advanced Camera, Tensor Chip",
    rating: 4.3,
    price: "$599.99",
    imgSrc: "./src/assets/image/google_pixel7_image.png",
  },
  {
    id: 12,
    name: "DJI Mini 3 Pro",
    description: "Compact Drone, 4K Video",
    rating: 3,
    price: "$759.99",
    imgSrc: "./src/assets/image/dji_mini3_image.png",
  },
  {
    id: 13,
    name: "Fitbit Charge 5",
    description: "Health Metrics, Built-in GPS",
    rating: 2,
    price: "$179.99",
    imgSrc: "./src/assets/image/fitbit_charge5_image.png",
  },
  {
    id: 14,
    name: "Apple Watch Series 8",
    description: "Advanced Health Tracking",
    rating: 4.6,
    price: "$399.99",
    imgSrc: "./src/assets/image/apple_watch8_image.jpg",
  },
  {
    id: 15,
    name: "Nintendo Switch OLED",
    description: "7-inch OLED Screen, Portable Gaming",
    rating: 3,
    price: "$349.99",
    imgSrc: "./src/assets/image/nintendo_switch_image.png",
  },
  {
    id: 16,
    name: "JBL Flip 6",
    description: "Portable Bluetooth Speaker",
    rating: 3.2,
    price: "$129.99",
    imgSrc: "./src/assets/image/jbl_flip6_image.png",
  },
  {
    id: 17,
    name: "Logitech MX Master 3",
    description: "Advanced Wireless Mouse",
    rating: 2.4,
    price: "$99.99",
    imgSrc: "./src/assets/image/logitech_mx_master3_image.png",
  },
  {
    id: 18,
    name: "Kindle Paperwhite",
    description: "Waterproof, High-resolution Display",
    rating: 3.2,
    price: "$139.99",
    imgSrc: "./src/assets/image/kindle_paperwhite_image.png",
  },
  {
    id: 19,
    name: "Razer BlackWidow V4",
    description: "Mechanical Gaming Keyboard",
    rating: 1.4,
    price: "$169.99",
    imgSrc: "./src/assets/image/razer_blackwidow_image.png",
  },
  {
    id: 20,
    name: "Samsung Galaxy Tab S8",
    description: "11-inch Display, S Pen Included",
    rating: 3,
    price: "$699.99",
    imgSrc: "./src/assets/image/samsung_tab_s8_image.png",
  },
];
